@EduLink.Api_HostAddress = https://localhost:7024

POST {{EduLink.Api_HostAddress}}/api/academies/{academyId}/courses
Content-Type: application/json

{
  //CreateCourseCommand
}

###
GET https://localhost:7024/api/academies/2/courses/1006 

GET {{EduLink.Api_HostAddress}}/api/academies
Authorization: Bearer {{$bearerToken}}

###
